### ISSUE TITLE
USEFUL TIPS for most errors: Read full post to avoid Kernal Cuda error and Tensor list expecting etc fixes.

### ISSUE THREAD

**Issue by simplyexperimental** [bytedance/LatentSync#299]
ORIGINAL POST:
*Followed various video guides and the github information but this tool is using very old dependencies which are not supported.
You going to have a horrible time finding the right cuda, cudnn, python and more versions it's horrible.

Got this installed on manually AND on comfyui and for all of them just error after error and never ended up working.

Even their online demo is broken I upload a video that's 8 seconds long and an audio thats 5 seconds long and it returns an error ON THEIR OWN DEMO.

Got it manually installed and still broken - the biggest problem is it uses a very old version of python which is breaking a lot of things.
Still after fixing python version I get more errors.

Got it comfyui portable still broken - main issue is comfyui uses 3.12 python and it's very difficult to get a 3.10 virtual environment too few documentation and resources available and no longer available versions to download that far back.

various kinds of errors - for manual install it couldn't get cuda available devices, then error then another error about expecting images etc.

for comfy UI it stuck on errors about omegacfg or something like that so the nodes never load.

Lost 15 hours today trying to wrestle it and gave up finally it's not worth it.

NEW POST: (See my second commend below)

**Comment by jbfilworks** [comment]
Still using it now. Working fine on Pinokio
https://github.com/Deepfake-Zatylkin/LatentSync-Pinokio?tab=readme-ov-file

**Comment by simplyexperimental** [comment]
I got it working just as I was about to give up.
What got it working for me was I needed to remove all conflicting python installations, cuda, cudnn and things like that.
I also did not create a virtual environment.

I installed it on Python 3.11, cuda 11.8, cuda 11 (one of the earlier versions), and the pytorch wheel was installed from the one in the notepad file. I had to use pip uninstall pytorch and then pip install pytorch using the link in the requirements file.
Finally got it working - but then went up against the tensor expecting non something error which I fixed by making the file names of the audio and video have no spaces etc "hello_123.mp4 and audio1.wav"

So finally after I got it working - the results just weren't very good despite the tweaking in settings. It has visual artifacts or just isn't a very good lipsync tool but it seems to work great for the samples, perhaps my videos are too close up?
Either way good learning experience setting it all up.

**Comment by kristopolous** [comment]
you can't have spaces in the file name ... it's crazy.  I should probably fix that.
